# Site settings
title: <span><img src="images/logo.jpg" width="33"/>&nbsp;&nbsp;Curso-R verão 2016 IME-USP</span>
email: athos.damiani@gmail.com
description: Material das aulas do curso de R
# > # this means to ignore newlines until "baseurl:"
# Material das aulas do Curso R, do casual ao avançado, 
# ministrado no Verão IME-USP 2016. O curso trata de 
# ferramentas contemporâneas para produção de análises 
# estatísticas, ajuste de modelos e elaboração de relatórios 
# estáticos e dinâmicos."



baseurl: "/verao2016" # the subpath of your site, e.g. /blog/
url: "http://curso-r.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: curso-r
permalink: /:title/

#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: curso-r
disqus_url: "http://curso-r.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
